
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftADDMINUSleftMULDIVnonassocPOWADD COMMENT DIV EOL ERROR EXPONENT LT_BR MINUS MOD MUL NUM POW RT_BR\n    ex2 : exp\n         | empty\n    \n    empty :\n    \n    exp  :    NUM                         \n            | MINUS NUM                 \n            | MINUS LT_BR exp RT_BR     \n            | LT_BR exp RT_BR           \n    \n    exp : exp ADD exp\n    \n    exp : exp MINUS exp \n    \n    exp : exp POW exponent\n    \n    exp : exp MUL exp\n    \n    exp : exp DIV exp\n    \n    exponent    : NUM                         \n                | MINUS NUM                 \n                | MINUS LT_BR exponent RT_BR     \n                | LT_BR exponent RT_BR           \n    \n    exponent : exponent ADD exponent\n    \n    exponent : exponent MINUS exponent \n    \n    exponent : exponent MUL exponent\n    \n    exponent : exponent DIV exponent\n    '
    
_lr_action_items = {'NUM':([0,5,6,7,8,9,10,11,13,19,20,25,26,27,28,30,],[4,12,4,4,4,18,4,4,4,29,18,18,18,18,18,18,]),'MINUS':([0,2,4,6,7,8,9,10,11,12,13,14,15,16,17,18,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,],[5,8,-4,5,5,5,19,5,5,-5,5,8,-8,-9,-10,-13,19,-11,-12,8,-7,19,19,19,19,-14,19,26,-6,-17,-18,-19,-20,26,-16,-15,]),'LT_BR':([0,5,6,7,8,9,10,11,13,19,20,25,26,27,28,30,],[6,13,6,6,6,20,6,6,6,30,20,20,20,20,20,20,]),'$end':([0,1,2,3,4,12,15,16,17,18,21,22,24,29,32,33,34,35,36,38,39,],[-3,0,-1,-2,-4,-5,-8,-9,-10,-13,-11,-12,-7,-14,-6,-17,-18,-19,-20,-16,-15,]),'ADD':([2,4,12,14,15,16,17,18,21,22,23,24,29,31,32,33,34,35,36,37,38,39,],[7,-4,-5,7,-8,-9,-10,-13,-11,-12,7,-7,-14,25,-6,-17,-18,-19,-20,25,-16,-15,]),'POW':([2,4,12,14,15,16,17,18,21,22,23,24,29,32,33,34,35,36,38,39,],[9,-4,-5,9,9,9,-10,-13,9,9,9,-7,-14,-6,-17,-18,-19,-20,-16,-15,]),'MUL':([2,4,12,14,15,16,17,18,21,22,23,24,29,31,32,33,34,35,36,37,38,39,],[10,-4,-5,10,10,10,-10,-13,-11,-12,10,-7,-14,27,-6,27,27,-19,-20,27,-16,-15,]),'DIV':([2,4,12,14,15,16,17,18,21,22,23,24,29,31,32,33,34,35,36,37,38,39,],[11,-4,-5,11,11,11,-10,-13,-11,-12,11,-7,-14,28,-6,28,28,-19,-20,28,-16,-15,]),'RT_BR':([4,12,14,15,16,17,18,21,22,23,24,29,31,32,33,34,35,36,37,38,39,],[-4,-5,24,-8,-9,-10,-13,-11,-12,32,-7,-14,38,-6,-17,-18,-19,-20,39,-16,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ex2':([0,],[1,]),'exp':([0,6,7,8,10,11,13,],[2,14,15,16,21,22,23,]),'empty':([0,],[3,]),'exponent':([9,20,25,26,27,28,30,],[17,31,33,34,35,36,37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ex2","S'",1,None,None,None),
  ('ex2 -> exp','ex2',1,'p_ex2','ex2.py',114),
  ('ex2 -> empty','ex2',1,'p_ex2','ex2.py',115),
  ('empty -> <empty>','empty',0,'p_empty','ex2.py',148),
  ('exp -> NUM','exp',1,'p_factor','ex2.py',154),
  ('exp -> MINUS NUM','exp',2,'p_factor','ex2.py',155),
  ('exp -> MINUS LT_BR exp RT_BR','exp',4,'p_factor','ex2.py',156),
  ('exp -> LT_BR exp RT_BR','exp',3,'p_factor','ex2.py',157),
  ('exp -> exp ADD exp','exp',3,'p_expADD','ex2.py',179),
  ('exp -> exp MINUS exp','exp',3,'p_expMINUS','ex2.py',188),
  ('exp -> exp POW exponent','exp',3,'p_expPOW','ex2.py',196),
  ('exp -> exp MUL exp','exp',3,'p_expMUL','ex2.py',205),
  ('exp -> exp DIV exp','exp',3,'p_expDIV','ex2.py',213),
  ('exponent -> NUM','exponent',1,'p_factorexponent','ex2.py',228),
  ('exponent -> MINUS NUM','exponent',2,'p_factorexponent','ex2.py',229),
  ('exponent -> MINUS LT_BR exponent RT_BR','exponent',4,'p_factorexponent','ex2.py',230),
  ('exponent -> LT_BR exponent RT_BR','exponent',3,'p_factorexponent','ex2.py',231),
  ('exponent -> exponent ADD exponent','exponent',3,'p_expADDexponent','ex2.py',253),
  ('exponent -> exponent MINUS exponent','exponent',3,'p_expMINUSexponent','ex2.py',262),
  ('exponent -> exponent MUL exponent','exponent',3,'p_expMULexponent','ex2.py',269),
  ('exponent -> exponent DIV exponent','exponent',3,'p_expDIVexponent','ex2.py',277),
]
