# coding: utf-8

"""
    Calculator

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.calculate_api import CalculateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCalculateApi(unittest.TestCase):
    """CalculateApi unit test stubs"""

    def setUp(self):
        self.api = CalculateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_number(self):
        """Test case for add_number

        Addition of two numbers  # noqa: E501
        """
        pass

    def test_div_number(self):
        """Test case for div_number

        Division of two numbers  # noqa: E501
        """
        pass

    def test_get_res(self):
        """Test case for get_res

        get result  # noqa: E501
        """
        pass

    def test_mul_number(self):
        """Test case for mul_number

        Multiplication of two numbers  # noqa: E501
        """
        pass

    def test_sub_number(self):
        """Test case for sub_number

        Subtraction of two numbers  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
